# Generated by Django 2.0.3 on 2018-03-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180312_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='dexc',
            new_name='desc',
        ),
    ]
