# Generated by Django 2.0.3 on 2018-03-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='phone',
            new_name='mobile',
        ),
    ]
