# Generated by Django 2.0.3 on 2018-03-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='defree',
            new_name='degree',
        ),
    ]
