# Generated by Django 2.0.3 on 2018-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('初级', 'cj'), ('终极', 'zj'), ('高级', 'gj')], max_length=2, verbose_name='等级'),
        ),
    ]
