# Generated by Django 2.0.3 on 2018-03-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avater',
            new_name='image',
        ),
    ]
